version: '3'
services:
  app:
    image: django:latest
    container_name: django_container
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/app
    depends_on:
      - postgres_db
    command: python manage.py runserver 0.0.0.0:8000

  postgres_db:
    image: postgres:15.3
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=socialApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres_db

volumes:
  db_data: