# Generated by Django 4.0.5 on 2022-12-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_followerrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users_avatar/default.jpg', null=True, upload_to='users_avatar'),
        ),
    ]
